### ISSUE TITLE
Server Maintenance Override for developers account

### ISSUE THREAD

**Issue by SEN-SENSATION** [SS-Developers/Timetables#15]
**Describe the feature request**

The server maintenance page should be overrideable with the developer account.
for debugging purposes.

**Additional context**

<img width="694" alt="Screen Shot 2565-05-27 at 11 01 37" src="https://user-images.githubusercontent.com/90727258/170627035-a503ef70-80c6-4eb2-b5fb-63dffaf678a3.png">

**Comment by Jiraties** [comment]
The feature request has been fulfilled and will be pushed intro production soon.
